In diesem Abschnitt werden wir eine logitische Regression vornehmen. Das Ziel ist es neue Kunden als Groß- oder Klein-Kunde klassifizieren zu können.
Dadurch können Großkunden spezifischer Angebote erhalten. Ein weitere Aspekt wäre die Maximierung des Umsatzes jedes Kunden, wodurch Klein-Kunden im Laufe der Zeit zum Groß-Kunden heranwachsen.

Die Kunden werden als Groß-Kunde klassifiziert wenn ihr durchschnittlicher Umsatz über dem Median liegt.
Als Klein-Kunde wenn er darunter liegt.
Hierfür haben wir dem Datensatz eine weiter Spalte als dummy_variable = Großkunde hinzugefügt.

In [38]:
import pandas as pd
import numpy as np

data = pd.read_csv('g:\\DHBW\\3. Semester\\BigData\\Logistische Regression\\Online Shop Customer Sales Data.csv')
data.head()

df = pd.DataFrame(data)
df = df.drop(columns=['Browser', 'Purchase_DATE', 'Customer_id'])
df.head()
df.corr()

# Korrelation zwischen Revenue_Total und Purchase_VALUE
df = df.drop(columns=['Purchase_VALUE'])

# Hinzufügen einer neuen Spalte (Großkunde 0/1)
median_revenue = df['Revenue_Total'].median()
df['Großkunde'] = np.where((df['Revenue_Total'] > median_revenue) & (df['N_Purchases'] > 3), 1,0) 
df.head()

,Age,Gender,Revenue_Total,N_Purchases,Pay_Method,Time_Spent,Newsletter,Voucher,Großkunde
0,53,0,45.3,2,1,885,0,0,0
1,18,1,36.2,3,2,656,0,1,0
2,52,1,10.6,1,0,761,1,0,0
3,29,0,54.1,5,1,906,1,0,1
4,21,1,56.9,1,1,605,1,0,0

Die Daten sind nun bereinigt und bereit für die logistische Regression.
Wir haben Daten mit kaum, bis gar keinen Einfluss auf unsere Output Variable Großkunde entfernt.
Außerdem haben wir die dummy_variable dem Datensatz hinzugefügt.

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# Aufteilen Input- und Output-Variablen

inputvar = df.drop(columns=['Großkunde'])
outputvar = df['Großkunde']

# Aufteilung in Trainings- und Testdaten

inputvar_train, inputvar_test, outputvar_train, outputvar_test = train_test_split(inputvar, outputvar, test_size=0.1, random_state=42)

logreg = LogisticRegression(max_iter=1000)
logreg.fit(inputvar_train, outputvar_train)

output_prediction = logreg.predict(inputvar_test)
genauigkeit = accuracy_score(outputvar_test, output_prediction)
print(f'Genauigkeit: {genauigkeit:.2f}')

confusion = confusion_matrix(outputvar_test, output_prediction)
print(confusion)

Genauigkeit: 0.88
[[4371  350]
 [ 427 1432]]